### ISSUE TITLE
compilation fails on "MSYS2 MSYS"

### ISSUE THREAD

**Issue by firewave** [danmar/simplecpp#476]
```
simplecpp.cpp: In function ‘std::string simplecpp::convertCygwinToWindowsPath(const std::string&)’:
simplecpp.cpp:2393:40: error: ‘startsWith_’ was not declared in this scope
 2393 |         if (cygwinPath.size() >= 11 && startsWith_(cygwinPath, "/cygdrive/")) {
      |
```

It works fine with "MSYS MINGW64".

**Comment by firewave** [comment]
This was introduced in #418. CC @Tal500
